defaults: &defaults
  base_url: "https://komin.malmo.se/"
  assets_url_base: "//assets.malmo.se/internal/v4/"
  auth_method: ldap # saml ldap or stub
  session_time: 30 # minutes

development: &development
  <<: *defaults
  cache_ttl: 1
  max_age: 0
  title_suffix: "MEKS (utveckling)"
  session_time: 1440
  auth_method: stub

local_test:
  <<: *development
  auth_method: stub

production: &production
  <<: *defaults
  cache_ttl: 43200
  max_age: 14400
  title_suffix: "MEKS"
  auth_method: saml

test:
  <<: *production
  title_suffix: "MEKS (test)"
  auth_method: saml
